#Error en tiempo de ejecucion durante el programa


numero, numero1 = 1,2
try:
    result = numero/2
except:
    print("error en el programa..")